[package]
name = "ye_olde_todos"
version = "0.2.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
clap = { version = "4.5.53", features = ["derive"] }
ignore = "0.4.25"
owo-colors = "4.2.3"
rayon = "1.10"
terminal_size = "0.4.3"
